sudo: false
dist: trusty
cache: bundler
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
before_install:
  - rvm use @global
  - gem uninstall bundler -x
  - gem install bundler --version=1.13.7
  - bundler --version
branches:
  only:
    - master
